### ISSUE TITLE
Build fails due to missing WKS_FILES

### ISSUE THREAD

**Issue by marcoguerri** [pcengines/meta-pcengines#10]
First, thank you for your great work across the board within the OSF community!

I understand `meta-pcengines` is highly WIP, but I was wondering whether I should expect for it to build at all. In fact, the build right now fails with:

```
ERROR: docker-image-minimal-1.0-r0 do_image_wic: No kickstart files from WKS_FILES were found: docker-image-minimal.pcengines-apu2.wks docker-image-minimal.wks. Please set WKS_FILE or WKS_FILES appropriately.
```

I don't see any `WKS_FILE` directive in the `pcengines-apu2` MACHINE config. There is a wic plugin under `scripts/lib/wic/plugins/source/bootimg-grub-legacy.py`, which however doesn't seem to be referenced by anything. 

I am definitely not an OE expert, but the layer seems to be incomplete. Could you elaborate on whether I am missing something obvious, or the layer is indeed incomplete?

Furthermore, the switch to `dunfell` missed upgrading the refspec for the other layers, so it fails very early due to layers incompatibility. 

I might be able to invest some time to open a PR to fix this, but before going there I'd like to understand if there is something I am missing with respect to WKS files, as it seems it could have never built without those.

Thank you!

**Comment by pietrushnic** [comment]
@marcoguerri would you mind sharing what kind of interesting product you create using this meta? Please note that despite maintaining that layer we do it non-profit. If you working on some professional projects feel free to [reach out](https://3mdeb.com/contact/). BTW we are registered and recognized [Yocto Participants](https://3mdeb.com/about-us/#we-are).

No matter your goals we will try to help you solve your issues since we using this layer in some projects.

**Comment by marcoguerri** [comment]
@pietrushnic My intention is to work on purely personal projects. I got an APU2D4, a TPM 2 (your own one from https://shop.3mdeb.com/product/tpm2/) and soon as set of miniPCI-e WiFi cards. I just want to build a thin layer on top of your meta-pcengines which implements a router/WiFi AP, VPN endpoint with keys backed by TPM. Really simple stuff, no rocket science and certainly not for profit. I like the idea of building it as an oe layer so that it's re-usable by just swapping the machine type. 

My question is really exploratory, I was trying to understand whether I am missing something obvious in the configuration of the layer as the build clearly fails for the reason mentioned above. 

I appreciate all your contribution to the OSF community and if I can help with my limited knowledge of oe (and limited time as a matter of fact), I would definitely give it a shot.

**Comment by pietrushnic** [comment]
@marcoguerri very interesting project. We did similar stuff adding also virtualization layer for separation needs, advanced security features like Verified boot (leveraging S-CRTM) and TrenchBoot (aka Trusted Boot aka D-RTM). If there would be public code or write up about your work please link it here. Presentation and blog posts related to what you doing:

* [Less-Insecure Network Edge Virtualization with Low Size, Weight and Power](https://3mdeb.com/events/#Platform-Security-Summit)
* [Secure Virtual Network Appliance](https://3mdeb.com/events/#Embedded-Linux-Conference)
* [WIP blog post: Open, innovative and extremely secure - OPNSense WiFi on PC Engines apu2   ](https://github.com/3mdeb/news-and-ideas/pull/204/files)

Good luck with your project.

**Comment by macpijan** [comment]
@marcoguerri We are using this layer in a few projects so it is in quite decent shape. But you are correct that there are some missing pieces in the WKS_FILE area. It is because of the fact we rarely use kas files or images from this layer - we rather use the specific images and wks files from project-specific layers.

This MR at least gets the image from `kas-docker.yml` to build correctly. Although I have not tested it on the hardware yet. https://github.com/pcengines/meta-pcengines/pull/11

**Comment by marcoguerri** [comment]
@macpijan That's great, thank you for fixing this so quickly. This is my weekend project, so I'll resume my experiments in few days :) 

If I understand correctly, you set WKS_FILE higher up in another layer (still in the machine config, I assume? So you don't use directly `pcengines-apu2.conf` in `meta-pcengines`?), that eventually references your own `bootimg-grub-legacy.py`? I must admit I am new to these concepts, so I am still figuring things out.

**Comment by marcoguerri** [comment]
#11 got me a bootable wic image that I could boot off an sd-card, with some tweaking to the kernel config. My intention is to share the simple layer I am building, as soon as I have some usable (might take a while :smile: ) Thank you again!
